javascript = [
    ["What does the following expression return?\n\t3 + 2;", "5", "'5'", "1", "Null", ""],
    ["What does the following expression return?\n\ttypeof(3);", "'number'", "'string'", "'integer'", "'int'",""],
    ["What does the following expression return?\n\ttypeof(3) === typeof(4.32);","true","false","nil","Error",""],
    ["What does the following expression return?\n\t3 / 'bob';","NaN","false","1","true",""],
    ["What does the following expression return?\n\tNaN === NaN;","false","true","nil","Error",""],
    ["What does the following expression return?\n\ttypeof(NaN);","'number'","'string'","'bool'","Error",""],
    ["What does the following expression return?\n\tisNaN(NaN);","true","false","nil","Error",""],
    ["What does the following expression return?\n\tMath.pow(2, 3);","8","9","1.5","6",""],
    ["What is the value of the hello variable in the following expression?\n\tvar hello;", "undefined","'hello'","nil","Error",""],
    ["What does the following expression return?\n\t'cool'.length;","4","2","nil","Error",""],
    ["What does the following expression return?\n\t6 / '2'","3","2","nil","Error",""],      
    ["What does the following expression return?\n\t3 * 'bob';","NaN","'bobbobbob'","9","Error",""],
    ["What does the following expression return?\n\ttypeof(3) === typeof(4.32);","true","false","nil","Error",""],
    ["What does the following expression return?\n\ttypeof(3) === typeof(4.32);","true","false","nil","Error",""],
    ["What does the following expression return?\n\ttypeof(3) === typeof(4.32);","true","false","nil","Error",""],
    ["What does the following expression return?\n\ttypeof(3) === typeof(4.32);","true","false","nil","Error",""],
    ["What does the following expression return?\n\ttypeof(3) === typeof(4.32);","true","false","nil","Error",""],
]